from enum import IntEnum
import pygame

EVENT_TYPES = ["QUIT","ACTIVEEVENT","KEYDOWN","KEYUP","MOUSEMOTION","MOUSEBUTTONUP","MOUSEBUTTONDOWN","VIDEORESIZE","VIDEOEXPOSE","AUDIODEVICEADDED","AUDIODEVICEREMOVED","FINGERMOTION","FINGERDOWN","FINGERUP","MOUSEWHEEL","MULTIGESTURE","TEXTEDITING","TEXTINPUT","DROPFILE","DROPBEGIN","DROPCOMPLETE","DROPTEXT","MIDIIN","MIDIOUT","CONTROLLERDEVICEADDED","JOYDEVICEADDED","CONTROLLERDEVICEREMOVED","JOYDEVICEREMOVED","CONTROLLERDEVICEREMAPPED","KEYMAPCHANGED","CLIPBOARDUPDATE","RENDER_TARGETS_RESET","RENDER_DEVICE_RESET","LOCALECHANGED","WINDOWSHOWN","WINDOWHIDDEN","WINDOWEXPOSED","WINDOWMOVED","WINDOWRESIZED","WINDOWSIZECHANGED","WINDOWMINIMIZED","WINDOWMAXIMIZED","WINDOWRESTORED","WINDOWENTER","WINDOWLEAVE","WINDOWFOCUSGAINED","WINDOWFOCUSLOST","WINDOWCLOSE","WINDOWTAKEFOCUS","WINDOWHITTEST","WINDOWICCPROFCHANGED","WINDOWDISPLAYCHANGED"]

EventType = IntEnum("EventType", [(et, pygame.__dict__[et]) for et in EVENT_TYPES] + [("COLLIDE", -1)])
