from .EventType import EventType
from .Event import Event
from .KeyType import KeyType

class EventFactory:
    @staticmethod
    def fromPygameEvent(event):
        #EVENTTYPES = [QUIT,ACTIVEEVENT,KEYDOWN,KEYUP,MOUSEMOTION,MOUSEBUTTONUP,MOUSEBUTTONDOWN,VIDEORESIZE,VIDEOEXPOSE,AUDIODEVICEADDED,AUDIODEVICEREMOVED,FINGERMOTION,FINGERDOWN,FINGERUP,MOUSEWHEEL,MULTIGESTURE,TEXTEDITING,TEXTINPUT,DROPFILE,DROPBEGIN,DROPCOMPLETE,DROPTEXT,MIDIIN,MIDIOUT,CONTROLLERDEVICEADDED,JOYDEVICEADDED,CONTROLLERDEVICEREMOVED,JOYDEVICEREMOVED,CONTROLLERDEVICEREMAPPED,KEYMAPCHANGED,CLIPBOARDUPDATE,RENDER_TARGETS_RESET,RENDER_DEVICE_RESET,LOCALECHANGED,WINDOWSHOWN,WINDOWHIDDEN,WINDOWEXPOSED,WINDOWMOVED,WINDOWRESIZED,WINDOWSIZECHANGED,WINDOWMINIMIZED,WINDOWMAXIMIZED,WINDOWRESTORED,WINDOWENTER,WINDOWLEAVE,WINDOWFOCUSGAINED,WINDOWFOCUSLOST,WINDOWCLOSE,WINDOWTAKEFOCUS,WINDOWHITTEST,WINDOWICCPROFCHANGED,WINDOWDISPLAYCHANGED]
        attr = event.__dict__
        if "key" in attr:
            try:
                attr["key"] = KeyType(attr["key"])
            except ValueError:
                attr["key"] = KeyType.UNKNOWN
        
        return Event(EventType(event.type), attr)
